# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbacea9f160241b2bfad1a1592c9f4a8a636a59d2d00fbf1034d3b904641b51d36eb70a73216e3bc857bcb07e82d6fdce2f59f254c12dd01aece8aed85731e3e

test:
  secret_key_base: 3789e3179d3485f46d70d9b72b5c0fdb9e0cb9915c7e5414b6652aacc1787ab9c3caa18521d3b305c3aa09190fec5cd130cfbc0e992aa609256965f9b9cc98a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
